-- ============================================================
-- Aggregations & Grouping
-- Questions 12-23
-- ============================================================

-- Q12: Calculate the total revenue.
-- Measure the overall sales generated by the company.
SELECT SUM(PaymentAmount) AS Revenue FROM Payments;

-- Q13: Find the average product price.
-- Analyze the average selling price of products.
SELECT AVG(Price) AS Average_Price FROM Products;

-- Q14: Find the highest order amount.
-- Identify the largest customer purchase.
SELECT MAX(PaymentAmount) AS Highest_Order_Amount FROM Payments;

-- Q15: Find the lowest product price.
-- Identify the least expensive product.
SELECT MIN(Price) AS Lowest_Product_Price
FROM Products;

-- Q16: Count the total number of products.
-- Determine the size of the product inventory.
SELECT COUNT(*) AS Total_Products
FROM Products;

-- Q17: Calculate revenue by category.
-- Identify which product categories generate the highest revenue.
SELECT c.CategoryName, SUM(oi.Quantity * oi.UnitPrice) AS Revenue
FROM Categories c
JOIN Products p
ON c.CategoryID = p.CategoryID
JOIN OrderItems oi
ON p.ProductID = oi.ProductID
GROUP BY c.CategoryName;

-- Q18: Count orders by city.
-- Compare customer order volumes across different cities.
SELECT c.City,COUNT(o.OrderID) AS Total_Orders
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
GROUP BY c.City;

-- Q19: Count orders handled by each employee.
-- Measure employee productivity.
SELECT e.EmployeeName, COUNT(o.OrderID) AS Total_Orders
FROM Employees e
LEFT JOIN Orders o
ON e.EmployeeID = o.EmployeeID
GROUP BY e.EmployeeName;

-- Q20: Count products supplied by each supplier.
-- Evaluate supplier contributions.
SELECT s.SupplierName, COUNT(p.ProductID) AS Total_Products
FROM Suppliers s
LEFT JOIN Products p
ON s.SupplierID = p.SupplierID
GROUP BY s.SupplierName;

-- Q21: Find cities having more than five customers.
-- Identify major customer locations.
SELECT City, COUNT(*) AS Total_Customers
FROM Customers
GROUP BY City
HAVING COUNT(*) > 5;

-- Q22: Find employees handling more than twenty orders.
-- Recognize employees with high workloads.
SELECT EmployeeID,COUNT(OrderID) AS Total_Orders
FROM Orders
GROUP BY EmployeeID
HAVING COUNT(OrderID) > 20;

-- Q23: Find categories generating revenue above ₹100,000.
-- Identify the best-performing product categories.
SELECT c.CategoryName, SUM(oi.Quantity * oi.UnitPrice) AS Revenue
FROM Categories c
JOIN Products p
ON c.CategoryID = p.CategoryID
JOIN OrderItems oi
ON p.ProductID = oi.ProductID
GROUP BY c.CategoryName
HAVING SUM(oi.Quantity * oi.UnitPrice) > 100000;
